# Generated by Django 5.1.3 on 2024-11-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_gallery_title_notice_date_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(),
        ),
    ]
